name: Weekly ETL Pipeline

on:
  schedule:
    # 매주 월요일 자정 NASDAQ 심볼 업데이트
    - cron: "0 0 * * 1"
    # 매주 일요일 오전 7시 재무 비율 데이터 수집
    - cron: "0 7 * * 0"
  workflow_dispatch: # 수동 실행 가능
    inputs:
      job_type:
        description: "ETL 작업 타입 선택"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - symbols
          - ratios

jobs:
  etl-symbols:
    if: github.event_name == 'schedule' || github.event.inputs.job_type == 'symbols' || github.event.inputs.job_type == 'all'
    runs-on: ubuntu-latest
    name: NASDAQ Symbols ETL

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run NASDAQ Symbols ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          DATA_API: ${{ secrets.DATA_API }}
        run: |
          echo "🚀 Starting NASDAQ Symbols ETL..."
          yarn etl:symbols
          echo "✅ NASDAQ Symbols ETL completed!"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: symbols-logs
          path: |
            *.log
            logs/

  etl-ratios:
    runs-on: ubuntu-latest
    name: Financial Ratios ETL
    needs: etl-symbols
    if: always() && (needs.etl-symbols.result == 'success' || needs.etl-symbols.result == 'skipped') && (github.event_name == 'schedule' || github.event.inputs.job_type == 'ratios' || github.event.inputs.job_type == 'all')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Financial Ratios ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          DATA_API: ${{ secrets.DATA_API }}
        run: |
          echo "🚀 Starting Financial Ratios ETL..."
          yarn etl:ratios
          echo "✅ Financial Ratios ETL completed!"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ratios-logs
          path: |
            *.log
            logs/

  notify-completion:
    if: always()
    runs-on: ubuntu-latest
    name: Notify Completion
    needs: [etl-symbols, etl-ratios]

    steps:
      - name: Notify Success
        if: needs.etl-symbols.result == 'success' && needs.etl-ratios.result == 'success'
        run: |
          echo "✅ Weekly ETL Pipeline completed successfully!"
          echo "📊 NASDAQ symbols and financial ratios updated"

      - name: Notify Failure
        if: needs.etl-symbols.result == 'failure' || needs.etl-ratios.result == 'failure'
        run: |
          echo "❌ Weekly ETL Pipeline failed!"
          echo "🔍 Check the logs for details"
          exit 1
